package com.xygame.sg.utils;

/**
 * Created by minhua on 2015/11/22.
 */
public class Country {
    public static final String txt = "[" +
            "{" +
            "\"country_code\":\"AD\"," +
            "\"country_name\":\"安道尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"AE\"," +
            "\"country_name\":\"阿拉伯联合酋长国\"" +
            "}," +
            "{" +
            "\"country_code\":\"AF\"," +
            "\"country_name\":\"阿富汗\"" +
            "}," +
            "{" +
            "\"country_code\":\"AG\"," +
            "\"country_name\":\"安提瓜和巴布达\"" +
            "}," +
            "{" +
            "\"country_code\":\"AI\"," +
            "\"country_name\":\"安圭拉\"" +
            "}," +
            "{" +
            "\"country_code\":\"AL\"," +
            "\"country_name\":\"阿尔巴尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"AM\"," +
            "\"country_name\":\"亚美尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"AO\"," +
            "\"country_name\":\"安哥拉\"" +
            "}," +
            "{" +
            "\"country_code\":\"AQ\"," +
            "\"country_name\":\"南极洲\"" +
            "}," +
            "{" +
            "\"country_code\":\"AR\"," +
            "\"country_name\":\"阿根廷\"" +
            "}," +
            "{" +
            "\"country_code\":\"AS\"," +
            "\"country_name\":\"美属萨摩亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"AT\"," +
            "\"country_name\":\"奥地利\"" +
            "}," +
            "{" +
            "\"country_code\":\"AU\"," +
            "\"country_name\":\"澳大利亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"AW\"," +
            "\"country_name\":\"阿鲁巴\"" +
            "}," +
            "{" +
            "\"country_code\":\"AX\"," +
            "\"country_name\":\"奥兰群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"AZ\"," +
            "\"country_name\":\"阿塞拜疆\"" +
            "}," +
            "{" +
            "\"country_code\":\"BA\"," +
            "\"country_name\":\"波斯尼亚和" +
            "黑塞哥维那\"" +
            "}," +
            "{" +
            "\"country_code\":\"BB\"," +
            "\"country_name\":\"巴巴多斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"BD\"," +
            "\"country_name\":\"孟加拉国\"" +
            "}," +
            "{" +
            "\"country_code\":\"BE\"," +
            "\"country_name\":\"比利时\"" +
            "}," +
            "{" +
            "\"country_code\":\"BF\"," +
            "\"country_name\":\"布基纳法索\"" +
            "}," +
            "{" +
            "\"country_code\":\"BG\"," +
            "\"country_name\":\"保加利亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"BH\"," +
            "\"country_name\":\"巴林\"" +
            "}," +
            "{" +
            "\"country_code\":\"BI\"," +
            "\"country_name\":\"布隆迪\"" +
            "}," +
            "{" +
            "\"country_code\":\"BJ\"," +
            "\"country_name\":\"贝宁\"" +
            "}," +
            "{" +
            "\"country_code\":\"BL\"," +
            "\"country_name\":\"圣巴泰勒米\"" +
            "}," +
            "{" +
            "\"country_code\":\"BM\"," +
            "\"country_name\":\"百慕大\"" +
            "}," +
            "{" +
            "\"country_code\":\"BN\"," +
            "\"country_name\":\"文莱\"" +
            "}," +
            "{" +
            "\"country_code\":\"BO\"," +
            "\"country_name\":\"玻利维亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"BQ\"," +
            "\"country_name\":\"荷兰加勒比区\"" +
            "}," +
            "{" +
            "\"country_code\":\"BR\"," +
            "\"country_name\":\"巴西\"" +
            "}," +
            "{" +
            "\"country_code\":\"BS\"," +
            "\"country_name\":\"巴哈马\"" +
            "}," +
            "{" +
            "\"country_code\":\"BT\"," +
            "\"country_name\":\"不丹\"" +
            "}," +
            "{" +
            "\"country_code\":\"BV\"," +
            "\"country_name\":\"布维岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"BW\"," +
            "\"country_name\":\"博茨瓦纳\"" +
            "}," +
            "{" +
            "\"country_code\":\"BY\"," +
            "\"country_name\":\"白俄罗斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"BZ\"," +
            "\"country_name\":\"伯利兹\"" +
            "}," +
            "{" +
            "\"country_code\":\"CA\"," +
            "\"country_name\":\"加拿大\"" +
            "}," +
            "{" +
            "\"country_code\":\"CC\"," +
            "\"country_name\":\"科科斯（基林）" +
            "群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"CD\"," +
            "\"country_name\":\"刚果（金）\"" +
            "}," +
            "{" +
            "\"country_code\":\"CF\"," +
            "\"country_name\":\"中非共和国\"" +
            "}," +
            "{" +
            "\"country_code\":\"CG\"," +
            "\"country_name\":\"刚果（布）\"" +
            "}," +
            "{" +
            "\"country_code\":\"CH\"," +
            "\"country_name\":\"瑞士\"" +
            "}," +
            "{" +
            "\"country_code\":\"CI\"," +
            "\"country_name\":\"科特迪瓦\"" +
            "}," +
            "{" +
            "\"country_code\":\"CK\"," +
            "\"country_name\":\"库克群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"CL\"," +
            "\"country_name\":\"智利\"" +
            "}," +
            "{" +
            "\"country_code\":\"CM\"," +
            "\"country_name\":\"喀麦隆\"" +
            "}," +
            "{" +
            "\"country_code\":\"CN\"," +
            "\"country_name\":\"中国\"" +
            "}," +
            "{" +
            "\"country_code\":\"CO\"," +
            "\"country_name\":\"哥伦比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"CR\"," +
            "\"country_name\":\"哥斯达黎加\"" +
            "}," +
            "{" +
            "\"country_code\":\"CU\"," +
            "\"country_name\":\"古巴\"" +
            "}," +
            "{" +
            "\"country_code\":\"CV\"," +
            "\"country_name\":\"佛得角\"" +
            "}," +
            "{" +
            "\"country_code\":\"CW\"," +
            "\"country_name\":\"库拉索\"" +
            "}," +
            "{" +
            "\"country_code\":\"CX\"," +
            "\"country_name\":\"圣诞岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"CY\"," +
            "\"country_name\":\"塞浦路斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"CZ\"," +
            "\"country_name\":\"捷克共和国\"" +
            "}," +
            "{" +
            "\"country_code\":\"DE\"," +
            "\"country_name\":\"德国\"" +
            "}," +
            "{" +
            "\"country_code\":\"DJ\"," +
            "\"country_name\":\"吉布提\"" +
            "}," +
            "{" +
            "\"country_code\":\"DK\"," +
            "\"country_name\":\"丹麦\"" +
            "}," +
            "{" +
            "\"country_code\":\"DM\"," +
            "\"country_name\":\"多米尼克\"" +
            "}," +
            "{" +
            "\"country_code\":\"DO\"," +
            "\"country_name\":\"多米尼加共和国" +
            "\"" +
            "}," +
            "{" +
            "\"country_code\":\"DZ\"," +
            "\"country_name\":\"阿尔及利亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"EC\"," +
            "\"country_name\":\"厄瓜多尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"EE\"," +
            "\"country_name\":\"爱沙尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"EG\"," +
            "\"country_name\":\"埃及\"" +
            "}," +
            "{" +
            "\"country_code\":\"EH\"," +
            "\"country_name\":\"西撒哈拉\"" +
            "}," +
            "{" +
            "\"country_code\":\"ER\"," +
            "\"country_name\":\"厄立特里亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"ES\"," +
            "\"country_name\":\"西班牙\"" +
            "}," +
            "{" +
            "\"country_code\":\"ET\"," +
            "\"country_name\":\"埃塞俄比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"FI\"," +
            "\"country_name\":\"芬兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"FJ\"," +
            "\"country_name\":\"斐济\"" +
            "}," +
            "{" +
            "\"country_code\":\"FK\"," +
            "\"country_name\":\"福克兰群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"FM\"," +
            "\"country_name\":\"密克罗尼西亚" +
            "\"" +
            "}," +
            "{" +
            "\"country_code\":\"FO\"," +
            "\"country_name\":\"法罗群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"FR\"," +
            "\"country_name\":\"法国\"" +
            "}," +
            "{" +
            "\"country_code\":\"GA\"," +
            "\"country_name\":\"加蓬\"" +
            "}," +
            "{" +
            "\"country_code\":\"GB\"," +
            "\"country_name\":\"英国\"" +
            "}," +
            "{" +
            "\"country_code\":\"GD\"," +
            "\"country_name\":\"格林纳达\"" +
            "}," +
            "{" +
            "\"country_code\":\"GE\"," +
            "\"country_name\":\"格鲁吉亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"GF\"," +
            "\"country_name\":\"法属圭亚那\"" +
            "}," +
            "{" +
            "\"country_code\":\"GG\"," +
            "\"country_name\":\"根西岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"GH\"," +
            "\"country_name\":\"加纳\"" +
            "}," +
            "{" +
            "\"country_code\":\"GI\"," +
            "\"country_name\":\"直布罗陀\"" +
            "}," +
            "{" +
            "\"country_code\":\"GL\"," +
            "\"country_name\":\"格陵兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"GM\"," +
            "\"country_name\":\"冈比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"GN\"," +
            "\"country_name\":\"几内亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"GP\"," +
            "\"country_name\":\"瓜德罗普\"" +
            "}," +
            "{" +
            "\"country_code\":\"GQ\"," +
            "\"country_name\":\"赤道几内亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"GR\"," +
            "\"country_name\":\"希腊\"" +
            "}," +
            "{" +
            "\"country_code\":\"GS\"," +
            "\"country_name\":\"南乔治亚岛和南桑威齐群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"GT\"," +
            "\"country_name\":\"危地马拉\"" +
            "}," +
            "{" +
            "\"country_code\":\"GU\"," +
            "\"country_name\":\"关岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"GW\"," +
            "\"country_name\":\"几内亚比绍\"" +
            "}," +
            "{" +
            "\"country_code\":\"GY\"," +
            "\"country_name\":\"圭亚那\"" +
            "}," +
            "{" +
            "\"country_code\":\"HK\"," +
            "\"country_name\":\"中国香港特" +
            "别行政区\"" +
            "}," +
            "{" +
            "\"country_code\":\"HM\"," +
            "\"country_name\":\"赫德岛和麦克唐纳群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"HN\"," +
            "\"country_name\":\"洪都拉斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"HR\"," +
            "\"country_name\":\"克罗地亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"HT\"," +
            "\"country_name\":\"海地\"" +
            "}," +
            "{" +
            "\"country_code\":\"HU\"," +
            "\"country_name\":\"匈牙利\"" +
            "}," +
            "{" +
            "\"country_code\":\"ID\"," +
            "\"country_name\":\"印度尼西亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"IE\"," +
            "\"country_name\":\"爱尔兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"IL\"," +
            "\"country_name\":\"以色列\"" +
            "}," +
            "{" +
            "\"country_code\":\"IM\"," +
            "\"country_name\":\"曼岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"IN\"," +
            "\"country_name\":\"印度\"" +
            "}," +
            "{" +
            "\"country_code\":\"IO\"," +
            "\"country_name\":\"英属印度洋领地\"" +
            "}," +
            "{" +
            "\"country_code\":\"IQ\"," +
            "\"country_name\":\"伊拉克\"" +
            "}," +
            "{" +
            "\"country_code\":\"IR\"," +
            "\"country_name\":\"伊朗\"" +
            "}," +
            "{" +
            "\"country_code\":\"IS\"," +
            "\"country_name\":\"冰岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"IT\"," +
            "\"country_name\":\"意大利\"" +
            "}," +
            "{" +
            "\"country_code\":\"JE\"," +
            "\"country_name\":\"泽西岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"JM\"," +
            "\"country_name\":\"牙买加\"" +
            "}," +
            "{" +
            "\"country_code\":\"JO\"," +
            "\"country_name\":\"约旦\"" +
            "}," +
            "{" +
            "\"country_code\":\"JP\"," +
            "\"country_name\":\"日本\"" +
            "}," +
            "{" +
            "\"country_code\":\"KE\"," +
            "\"country_name\":\"肯尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"KG\"," +
            "\"country_name\":\"吉尔吉斯斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"KH\"," +
            "\"country_name\":\"柬埔寨\"" +
            "}," +
            "{" +
            "\"country_code\":\"KI\"," +
            "\"country_name\":\"基里巴斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"KM\"," +
            "\"country_name\":\"科摩罗\"" +
            "}," +
            "{" +
            "\"country_code\":\"KN\"," +
            "\"country_name\":\"圣基茨和尼维斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"KP\"," +
            "\"country_name\":\"朝鲜\"" +
            "}," +
            "{" +
            "\"country_code\":\"KR\"," +
            "\"country_name\":\"韩国\"" +
            "}," +
            "{" +
            "\"country_code\":\"KW\"," +
            "\"country_name\":\"科威特\"" +
            "}," +
            "{" +
            "\"country_code\":\"KY\"," +
            "\"country_name\":\"开曼群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"KZ\"," +
            "\"country_name\":\"哈萨克斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"LA\"," +
            "\"country_name\":\"老挝\"" +
            "}," +
            "{" +
            "\"country_code\":\"LB\"," +
            "\"country_name\":\"黎巴嫩\"" +
            "}," +
            "{" +
            "\"country_code\":\"LC\"," +
            "\"country_name\":\"圣卢西亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"LI\"," +
            "\"country_name\":\"列支敦士登\"" +
            "}," +
            "{" +
            "\"country_code\":\"LK\"," +
            "\"country_name\":\"斯里兰卡\"" +
            "}," +
            "{" +
            "\"country_code\":\"LR\"," +
            "\"country_name\":\"利比里亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"LS\"," +
            "\"country_name\":\"莱索托\"" +
            "}," +
            "{" +
            "\"country_code\":\"LT\"," +
            "\"country_name\":\"立陶宛\"" +
            "}," +
            "{" +
            "\"country_code\":\"LU\"," +
            "\"country_name\":\"卢森堡\"" +
            "}," +
            "{" +
            "\"country_code\":\"LV\"," +
            "\"country_name\":\"拉脱维亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"LY\"," +
            "\"country_name\":\"利比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"MA\"," +
            "\"country_name\":\"摩洛哥\"" +
            "}," +
            "{" +
            "\"country_code\":\"MC\"," +
            "\"country_name\":\"摩纳哥\"" +
            "}," +
            "{" +
            "\"country_code\":\"MD\"," +
            "\"country_name\":\"摩尔多瓦\"" +
            "}," +
            "{" +
            "\"country_code\":\"ME\"," +
            "\"country_name\":\"黑山\"" +
            "}," +
            "{" +
            "\"country_code\":\"MF\"," +
            "\"country_name\":\"法属圣马丁\"" +
            "}," +
            "{" +
            "\"country_code\":\"MG\"," +
            "\"country_name\":\"马达加斯加\"" +
            "}," +
            "{" +
            "\"country_code\":\"MH\"," +
            "\"country_name\":\"马绍尔群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"MK\"," +
            "\"country_name\":\"马其顿\"" +
            "}," +
            "{" +
            "\"country_code\":\"ML\"," +
            "\"country_name\":\"马里\"" +
            "}," +
            "{" +
            "\"country_code\":\"MM\"," +
            "\"country_name\":\"缅甸\"" +
            "}," +
            "{" +
            "\"country_code\":\"MN\"," +
            "\"country_name\":\"蒙古\"" +
            "}," +
            "{" +
            "\"country_code\":\"MO\"," +
            "\"country_name\":\"中国澳门特别行政区\"" +
            "}," +
            "{" +
            "\"country_code\":\"MP\"," +
            "\"country_name\":\"北马里亚纳群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"MQ\"," +
            "\"country_name\":\"马提尼克\"" +
            "}," +
            "{" +
            "\"country_code\":\"MR\"," +
            "\"country_name\":\"毛里塔尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"MS\"," +
            "\"country_name\":\"蒙特塞拉特\"" +
            "}," +
            "{" +
            "\"country_code\":\"MT\"," +
            "\"country_name\":\"马耳他\"" +
            "}," +
            "{" +
            "\"country_code\":\"MU\"," +
            "\"country_name\":\"毛里求斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"MV\"," +
            "\"country_name\":\"马尔代夫\"" +
            "}," +
            "{" +
            "\"country_code\":\"MW\"," +
            "\"country_name\":\"马拉维\"" +
            "}," +
            "{" +
            "\"country_code\":\"MX\"," +
            "\"country_name\":\"墨西哥\"" +
            "}," +
            "{" +
            "\"country_code\":\"MY\"," +
            "\"country_name\":\"马来西亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"MZ\"," +
            "\"country_name\":\"莫桑比克\"" +
            "}," +
            "{" +
            "\"country_code\":\"NA\"," +
            "\"country_name\":\"纳米比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"NC\"," +
            "\"country_name\":\"新喀里多尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"NE\"," +
            "\"country_name\":\"尼日尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"NF\"," +
            "\"country_name\":\"诺福克岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"NG\"," +
            "\"country_name\":\"尼日利亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"NI\"," +
            "\"country_name\":\"尼加拉瓜\"" +
            "}," +
            "{" +
            "\"country_code\":\"NL\"," +
            "\"country_name\":\"荷兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"NO\"," +
            "\"country_name\":\"挪威\"" +
            "}," +
            "{" +
            "\"country_code\":\"NP\"," +
            "\"country_name\":\"尼泊尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"NR\"," +
            "\"country_name\":\"瑙鲁\"" +
            "}," +
            "{" +
            "\"country_code\":\"NU\"," +
            "\"country_name\":\"纽埃\"" +
            "}," +
            "{" +
            "\"country_code\":\"NZ\"," +
            "\"country_name\":\"新西兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"OM\"," +
            "\"country_name\":\"阿曼\"" +
            "}," +
            "{" +
            "\"country_code\":\"PA\"," +
            "\"country_name\":\"巴拿马\"" +
            "}," +
            "{" +
            "\"country_code\":\"PE\"," +
            "\"country_name\":\"秘鲁\"" +
            "}," +
            "{" +
            "\"country_code\":\"PF\"," +
            "\"country_name\":\"法属波利尼西亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"PG\"," +
            "\"country_name\":\"巴布亚新几内亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"PH\"," +
            "\"country_name\":\"菲律宾\"" +
            "}," +
            "{" +
            "\"country_code\":\"PK\"," +
            "\"country_name\":\"巴基斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"PL\"," +
            "\"country_name\":\"波兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"PM\"," +
            "\"country_name\":\"圣皮埃尔和密克隆群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"PN\"," +
            "\"country_name\":\"皮" +
            "特凯恩群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"PR\"," +
            "\"country_name\":\"波多黎各\"" +
            "}," +
            "{" +
            "\"country_code\":\"PS\"," +
            "\"country_name\":\"巴勒斯坦领土\"" +
            "}," +
            "{" +
            "\"country_code\":\"PT\"," +
            "\"country_name\":\"葡萄牙\"" +
            "}," +
            "{" +
            "\"country_code\":\"PW\"," +
            "\"country_name\":\"帕劳\"" +
            "}," +
            "{" +
            "\"country_code\":\"PY\"," +
            "\"country_name\":\"巴拉圭\"" +
            "}," +
            "{" +
            "\"country_code\":\"QA\"," +
            "\"country_name\":\"卡塔尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"RE\"," +
            "\"country_name\":\"留尼汪\"" +
            "}," +
            "{" +
            "\"country_code\":\"RO\"," +
            "\"country_name\":\"罗马尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"RS\"," +
            "\"country_name\":\"塞尔维亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"RU\"," +
            "\"country_name\":\"俄罗斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"RW\"," +
            "\"country_name\":\"卢旺达\"" +
            "}," +
            "{" +
            "\"country_code\":\"SA\"," +
            "\"country_name\":\"沙特阿拉伯\"" +
            "}," +
            "{" +
            "\"country_code\":\"SB\"," +
            "\"country_name\":\"所罗门群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"SC\"," +
            "\"country_name\":\"塞舌尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"SD\"," +
            "\"country_name\":\"苏丹\"" +
            "}," +
            "{" +
            "\"country_code\":\"SE\"," +
            "\"country_name\":\"瑞典\"" +
            "}," +
            "{" +
            "\"country_code\":\"SG\"," +
            "\"country_name\":\"新加坡\"" +
            "}," +
            "{" +
            "\"country_code\":\"SH\"," +
            "\"country_name\":\"圣赫勒拿\"" +
            "}," +
            "{" +
            "\"country_code\":\"SI\"," +
            "\"country_name\":\"斯洛文尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"SJ\"," +
            "\"country_name\":\"斯瓦尔巴特和扬马延\"" +
            "}," +
            "{" +
            "\"country_code\":\"SK\"," +
            "\"country_name\":\"斯洛伐克\"" +
            "}," +
            "{" +
            "\"country_code\":\"SL\"," +
            "\"country_name\":\"" +
            "塞拉利昂\"" +
            "}," +
            "{" +
            "\"country_code\":\"SM\"," +
            "\"country_name\":\"圣马力诺\"" +
            "}," +
            "{" +
            "\"country_code\":\"SN\"," +
            "\"country_name\":\"塞内加尔\"" +
            "}," +
            "{" +
            "\"country_code\":\"SO\"," +
            "\"country_name\":\"索马里\"" +
            "}," +
            "{" +
            "\"country_code\":\"SR\"," +
            "\"country_name\":\"苏里南\"" +
            "}," +
            "{" +
            "\"country_code\":\"SS\"," +
            "\"country_name\":\"南苏丹\"" +
            "}," +
            "{" +
            "\"country_code\":\"ST\"," +
            "\"country_name\":\"圣多美和普林西比\"" +
            "}," +
            "{" +
            "\"country_code\":\"SV\"," +
            "\"country_name\":\"萨尔" +
            "瓦多\"" +
            "}," +
            "{" +
            "\"country_code\":\"SX\"," +
            "\"country_name\":\"荷属圣马丁\"" +
            "}," +
            "{" +
            "\"country_code\":\"SY\"," +
            "\"country_name\":\"叙利亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"SZ\"," +
            "\"country_name\":\"斯威士兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"TC\"," +
            "\"country_name\":\"特克斯和凯科斯群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"TD\"," +
            "\"country_name\":\"乍得\"" +
            "}," +
            "{" +
            "\"country_code\":\"TF\"," +
            "\"country_name\":\"法属南部领地\"" +
            "}," +
            "{" +
            "\"country_code\":\"TG\"," +
            "\"country_name\":\"多哥\"" +
            "}," +
            "{" +
            "\"country_code\":\"TH\"," +
            "\"country_name\":\"泰国\"" +
            "}," +
            "{" +
            "\"country_code\":\"TJ\"," +
            "\"country_name\":\"塔吉克斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"TK\"," +
            "\"country_name\":\"托克劳\"" +
            "}," +
            "{" +
            "\"country_code\":\"TL\"," +
            "\"country_name\":\"东帝汶\"" +
            "}," +
            "{" +
            "\"country_code\":\"TM\"," +
            "\"country_name\":\"土库曼斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"TN\"," +
            "\"country_name\":\"突尼斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"TO\"," +
            "\"country_name\":\"汤加\"" +
            "}," +
            "{" +
            "\"country_code\":\"TR\"," +
            "\"country_name\":\"土耳其\"" +
            "}," +
            "{" +
            "\"country_code\":\"TT\"," +
            "\"country_name\":\"特立尼达和多巴哥\"" +
            "}," +
            "{" +
            "\"country_code\":\"TV\"," +
            "\"country_name\":\"图瓦卢\"" +
            "}," +
            "{" +
            "\"country_code\":\"TW\"," +
            "\"country_name\":\"中国台湾\"" +
            "}," +
            "{" +
            "\"country_code\":\"TZ\"," +
            "\"country_name\":\"坦桑尼亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"UA\"," +
            "\"country_name\":\"乌克兰\"" +
            "}," +
            "{" +
            "\"country_code\":\"UG\"," +
            "\"country_name\":\"乌干达\"" +
            "}," +
            "{" +
            "\"country_code\":\"UM\"," +
            "\"country_name\":\"美国本土外小岛屿\"" +
            "}," +
            "{" +
            "\"country_code\":\"US\"," +
            "\"country_name\":\"美国\"" +
            "}," +
            "{" +
            "\"country_code\":\"UY\"," +
            "\"country_name\":\"乌拉圭\"" +
            "}," +
            "{" +
            "\"country_code\":\"UZ\"," +
            "\"country_name\":\"乌兹别克斯坦\"" +
            "}," +
            "{" +
            "\"country_code\":\"VA\"," +
            "\"country_name\":\"梵蒂冈\"" +
            "}," +
            "{" +
            "\"country_code\":\"VC\"," +
            "\"country_name\":\"圣文森特和格林纳丁斯\"" +
            "}," +
            "{" +
            "\"country_code\":\"VE\"," +
            "\"country_name\":\"委内瑞拉\"" +
            "}," +
            "{" +
            "\"country_code\":\"VG\"," +
            "\"country_name\":\"英属维京群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"VI\"," +
            "\"country_name\":\"美属维京群岛\"" +
            "}," +
            "{" +
            "\"country_code\":\"VN\"," +
            "\"country_name\":\"越南\"" +
            "}," +
            "{" +
            "\"country_code\":\"VU\"," +
            "\"country_name\":\"瓦努阿图\"" +
            "}," +
            "{" +
            "\"country_code\":\"WF\"," +
            "\"country_name\":\"瓦利斯和富图纳\"" +
            "}," +
            "{" +
            "\"country_code\":\"WS\"," +
            "\"country_name\":\"萨摩亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"YE\"," +
            "\"country_name\":\"也门\"" +
            "}," +
            "{" +
            "\"country_code\":\"YT\"," +
            "\"country_name\":\"马约特\"" +
            "}," +
            "{" +
            "\"country_code\":\"ZA\"," +
            "\"country_name\":\"南非\"" +
            "}," +
            "{" +
            "\"country_code\":\"ZM\"," +
            "\"country_name\":\"赞比亚\"" +
            "}," +
            "{" +
            "\"country_code\":\"ZW\"," +
            "\"country_name\":\"津巴布韦\"" +
            "}" +
            "]";

}
